### ISSUE TITLE
01. WAP To Print First 10 Even Number ?

### ISSUE THREAD

**Issue by MadJokkerr** [MadJokkerr/Hacktoberfest-2022#1]

**Comment by ashutoshmp1** [comment]
Hey, can I contribute here and on other issues?

**Comment by arkapg211002** [comment]
@MadJokkerr I want to contribute this in java can u pls assign me

**Comment by MadJokkerr** [comment]
ohk @arkapg211002

**Comment by sujeettomar60615** [comment]
@MadJokkerr Hey Can u assign this issue to me in C++ ?

**Comment by MadJokkerr** [comment]
ohk @sujeettomar60615 you can contribute in c++

**Comment by charu210703** [comment]
@MadJokkerr Can I contribute in python?

**Comment by MadJokkerr** [comment]
> @MadJokkerr Can I contribute in python?

Yes @charu210703

**Comment by harkar20** [comment]
i want to work on this issue, please assign it to me

**Comment by MadJokkerr** [comment]
> i want to work on this issue, please assign it to me

which lang in which you wanna contribute

**Comment by tanishqvashisht** [comment]
can i contribute to this in python?

**Comment by MadJokkerr** [comment]
> can i contribute to this in python?

ohk @tanishqvashisht

**Comment by charu210703** [comment]
I have made the PR #96 for this. Kindly have a look that at and merge it.

**Comment by MadJokkerr** [comment]
> I have made the PR #96 for this. Kindly have a look that at and merge it.

sorry next time i assigned you work and you didn't work on it now its someone else turn

**Comment by charu210703** [comment]
Sorry, but If the python version of issue 4 is free or if it becomes free, can you assign it to me?

**Comment by MadJokkerr** [comment]
> Sorry, but If the python version of issue 4 is free or if it becomes free, can you assign it to me?

What You Mean By Python Version of issue 4

**Comment by charu210703** [comment]
python code for WAP To Print the Nth Even Number. As you have assigned that issue to the concerned person yesterday and its not closed till now, that's why I asked?

**Comment by MadJokkerr** [comment]
> python code for WAP To Print the Nth Even Number. As you have assigned that issue to the concerned person yesterday and its not closed till now, that's why I asked?

yeah sure @charu210703 i will assign you but as far as i know you did some contribution in code time line why didn't you try to do some non-code(documentation) work i will suggest to go for some 'Documentation' tags

**Comment by MadJokkerr** [comment]
ohk charu work on this issue

**Comment by charu210703** [comment]
> ohk charu work on this issue

Done! #102. Thanks for letting me contribute.
