### ISSUE TITLE
10. WAP To Find Largest Of Three Numbers ?

### ISSUE THREAD

**Issue by MadJokkerr** [MadJokkerr/Hacktoberfest-2022#10]

**Comment by arkapg211002** [comment]
Hello can I contribute?

**Comment by MadJokkerr** [comment]
> Hello can I contribute?

@arkapg211002 Yes go a head But remember follow label/paths & how to write code you can refer code examples

**Comment by MadJokkerr** [comment]
> Hello can I contribute?

In which lang you wanna contribute?

**Comment by arkapg211002** [comment]
I would like to contribute in java

**Comment by arkapg211002** [comment]
@MadJokkerr Hello, I have made 4 PRs. Please tell me whether I have to make any changes or not, or if anything is wrong

1. [WAP to print first 10 even numbers](https://github.com/MadJokkerr/Hacktoberfest-2022/pull/50)
2. [WAP to print first 10 odd numbers](https://github.com/MadJokkerr/Hacktoberfest-2022/pull/51)
3. [WAP to print right angle triangle up to N stars](https://github.com/MadJokkerr/Hacktoberfest-2022/pull/52)
4. [WAP to print the Nth even number](https://github.com/MadJokkerr/Hacktoberfest-2022/pull/53)

I was also going through the contributing guidelines. It said to add details
so I have added here [CONTRIBUTORS.md](https://github.com/MadJokkerr/Hacktoberfest-2022/pull/48) and made a PR(not sure whether it has to be actually done by me or not)

**Comment by arkapg211002** [comment]
@MadJokkerr Please assign me this issue.. i would like to contribute in java

**Comment by sujeettomar60615** [comment]
@MadJokkerr Hey Can u assign this issue to me in C++ ?

**Comment by MadJokkerr** [comment]
> @MadJokkerr Please assign me this issue.. i would like to contribute in java

ohk go a head in java language @MadJokkerr

**Comment by MadJokkerr** [comment]
> @MadJokkerr Hey Can u assign this issue to me in C++ ?

ohk @sujeettomar60615 in C++ lang

**Comment by latedeveloper08** [comment]
I like to contribute in this if you allow

**Comment by MadJokkerr** [comment]
ohk @latedeveloper08

**Comment by harkar20** [comment]
i want to work on this issue, please assign it to me

**Comment by MadJokkerr** [comment]
> i want to work on this issue, please assign it to me

this issue is about to close you can find another issues in repo
@harkar20
