### ISSUE TITLE
11. WAP To Print Fibonacci series?

### ISSUE THREAD

**Issue by MadJokkerr** [MadJokkerr/Hacktoberfest-2022#11]
Write a program that will print fibonacci series upto N

**Comment by arkapg211002** [comment]
Hey Can I contribute?

**Comment by arkapg211002** [comment]
Can I contribute to the other issues?

**Comment by ashutoshmp1** [comment]
Hey, can I contribute here and on other issues?

**Comment by arkapg211002** [comment]
@MadJokkerr Hello can u pls assign me this issue , I would like to contribute in java

**Comment by sujeettomar60615** [comment]
@MadJokkerr Hey Can u assign this issue to me in C++ ?

**Comment by MadJokkerr** [comment]
> @MadJokkerr Hello can u pls assign me this issue , I would like to contribute in java

ohk contribute in java

**Comment by MadJokkerr** [comment]
> @MadJokkerr Hey Can u assign this issue to me in C++ ?

ohk @sujeettomar60615 in c++

**Comment by latedeveloper08** [comment]
Hey I want to contribute to this issue in python language!

**Comment by MadJokkerr** [comment]
> Hey I want to contribute to this issue in python language!

Ohk @latedeveloper08 go a head in python lang
