### ISSUE TITLE
4. WAP To Print the Nth Even Number ?

### ISSUE THREAD

**Issue by MadJokkerr** [MadJokkerr/Hacktoberfest-2022#4]
Write a program That will print the Nth Even Number which basically means that the  number given by the user will print the even number come on that place 
For eg: 
10/2 which gives 5
So if User drop n=5 Then the program will return 10 as the output

**Comment by xx-abhijeet-xx** [comment]
Hey, Can I contribute?

**Comment by xx-abhijeet-xx** [comment]
can you assign this issue to me?

**Comment by MadJokkerr** [comment]
> can you assign this issue to me?

Ohk @xx-abhijeet-xx 
which lang You want to work in ?

**Comment by xx-abhijeet-xx** [comment]
> 

C++ @MadJokkerr

**Comment by MadJokkerr** [comment]
@Soullessmars Ohk contribute in java Folder

**Comment by MadJokkerr** [comment]
> I want to contribute to this issue in python language

ohk @latedeveloper08 contribute in python dir

**Comment by harkar20** [comment]
i want to work on this issue, please assign it to me

**Comment by MadJokkerr** [comment]
> i want to work on this issue, please assign it to me

the issue is closed work on different issue @harkar20
