### ISSUE TITLE
43. Create a cheat sheet for Numpy lib in ipynb file ?

### ISSUE THREAD

**Issue by MadJokkerr** [MadJokkerr/Hacktoberfest-2022#67]

**Comment by mayanksharma-1** [comment]
I have experience with NumPy lib and  inpynb files, I can work on this issue.

**Comment by MadJokkerr** [comment]
ohk work on it @mayanksharma-1 make a .ipynb file which is easy to read and understand and also covers most of the methods and techniques of numpy make file in Hacktoberfest-2022/Documentation/Interactive Notebook/Python Modules folder also follow code of conduct and contribtion guidelines and don't forget to read readme file and add your name to contributors.md
