### ISSUE TITLE
44. What is Supervisied Machine Learning Technique ?

### ISSUE THREAD

**Issue by MadJokkerr** [MadJokkerr/Hacktoberfest-2022#68]
This Documentation Cover Following Points: 
1. Explain This Machine Learning Techniques
2. What type of Data Set is Requried 
3. How Computer Learn
4. Types of Algorithms Used

Put The File In Markdown Format

**Comment by girijakar** [comment]
I would like to work on this issue.

**Comment by MadJokkerr** [comment]
@girijakar ohk

**Comment by girijakar** [comment]
#87
